### ISSUE TITLE
P1858 Generalized pack declaration and usage

### ISSUE THREAD

**Issue by brevzin** [brevzin/cpp_proposals#107]
[P1858R2 Generalized pack declaration and usage](https://brevzin.github.io/cpp_proposals/1858_generalized_packs/p1858r2.html)

https://github.com/cplusplus/papers/issues/612

**Comment by AbhinavK00** [comment]
Hello, I could not think of any other way to ask questions/provide feedback, so I thought of using issues. I have been reading some of your proposals about packs, mainly P2671, P1858 and the latest one P2994 and I have not been able to wrap my head around some things. 

1)How does P2994 interact with P2671. Does it fully supersede the latter? If yes, then there are points which the former one does not address. I think the answer is yes, but the question is worth asking.

2) Have you considered the possibility that slicing a tuple returns a sub-tuple itself? While this does not seem the right choice currently, if P2163 gets accepted (which has low chances as it has no recent revision), then returning sub-tuples would be a better choice.

3) P2671 section 2.1 talks about how `return (x.elems + ...)` cannot work today and provides some syntax choices to solve the problem. Can you please explain why does it not work and how the proposed solutions solve the problem?

4) P2671 says that there is a desire for some kind of prefix to indicate that a pack expansion follows and same for fold expressions. But isn't this... less generic? Code outside and inside of template will have to be written differently and when more pack operations are added (indexing, slicing etc.), uses of those would also have to be placed inside of "pack expansion blocks". Isn't it better that code inside and outside of templates looks the same.

5) P1858 section 6.1 says the first example is ill-formed while it works. [Link to Godbolt](https://godbolt.org/z/MY4qKcroq).

I'm really sorry if this is not the right place to ask questions, hope you don't mind.
