### ISSUE TITLE
Links in README should be to rendered versions

### ISSUE THREAD

**Issue by eyalroz** [brevzin/cpp_proposals#38]
The links from README.md give us a page with the proposal source. Which is basically a lot of boilerplate CSS before we get anywhere.

Instead, the links should lead to the HTML of the proposal, with a text/HTML MIME type, so that the browser would actually display it.

**Comment by brevzin** [comment]
They do on the rendered readme.

**Comment by eyalroz** [comment]
@brevzin : Uh, no, they don't.

**Comment by brevzin** [comment]
> @brevzin : Uh, no, they don't.

Yes, they do, on the [rendered readme](https://brevzin.github.io/cpp_proposals/).
