### ISSUE TITLE
P0312 Making Pointers to Members Callable

### ISSUE THREAD

**Issue by brevzin** [brevzin/cpp_proposals#45]
[P0312R1 - Making Pointers to Members Callable](https://brevzin.github.io/cpp_proposals/0312_pointers_to_members/p0312r1.html).

**Comment by brevzin** [comment]
R0 rejected in [Oulu](https://wiki.edg.com/bin/view/Wg21oulu/P0312R0).
R1 rejected in [Toronto](https://wiki.edg.com/bin/view/Wg21toronto2017/P0312R1).

**Comment by atomgalaxy** [comment]
Can we reopen this one?

We actually need to bring this back.

**Comment by brevzin** [comment]
I'm mostly doing this to help me keep track of papers - only added half of them so far. 

Anyway, for this specifically, the one (singular) issue really is that in order to replace `std::invoke`, this needs to work:

```cpp
struct C { int foo(); };

int main() {
    C c;
    auto f = &C::foo;

    // obviously this is fine
    f(c);

    // this isn't particularly problematic either, if we specify the rules in terms of
    // conversion to C&, not specifically in terms of std::reference_wrapper<T>
    // which makes total sense if you think about C::foo as taking a C&
    f(std::ref(c)); 

    // this one is actually quite weird
    f(&c);
}
```

If you don't support the last one, then it's not actually replacing `std::invoke` and all the corresponding machinery (which now also includes all the concepts and everything in `std::ranges`).  It's unfortunate in retrospect that _`INVOKE`_ did this. 

But yeah besides that, there's basically no reason to not do this, except just having to deal with it.

**Comment by atomgalaxy** [comment]
Thanks for making that explicit - I thought it was something like that, but
realistically, since you know C, we could just flat out define that by fiat.
