### ISSUE TITLE
P2758 Emitting messages at compile time

### ISSUE THREAD

**Issue by brevzin** [brevzin/cpp_proposals#58]
[P2758R0 - Emitting messages at compile time](https://brevzin.github.io/cpp_proposals/2758_compile_time_messages/p2758r0.html).

https://github.com/cplusplus/papers/issues/1445

**Comment by frederick-vs-ja** [comment]
It seems that `constexpr_error_str` shouldn't be a constexpr function as it unconditionally causes contant evaluation failure.

**Comment by brevzin** [comment]
> It seems that `constexpr_error_str` shouldn't be a constexpr function as it unconditionally causes contant evaluation failure.
> 
> Edit: oh, I guess the intent is allowing constant expression evaluator to enter the function body and execute some builtin...

Yeah I need it to be ill-formed because the call emits a diagnostic and fails, not ill-formed because we just called some non-constexpr function - otherwise I wouldn't get the diagnostic I need.
