### ISSUE TITLE
P2011 A pipeline-rewrite operator

### ISSUE THREAD

**Issue by brevzin** [brevzin/cpp_proposals#82]
[D2011R2 - A pipeline-rewrite operator](https://brevzin.github.io/cpp_proposals/2011_pipeline/d2011r2.html)

https://github.com/cplusplus/papers/issues/748

**Comment by Klaim** [comment]
Hi! I was looking for news about this paper, I see you have a revision since 2023 ready but I don't see it published yet. Is there some blocking issues?

**Comment by Klaim** [comment]
Note for future me: the polls for P2672 essentially blocked the progress on this.
https://github.com/cplusplus/papers/issues/1338
